CC=gcc
CFLAGS=
LDFLAGS=

#Application Source
C_SOURCE_FILES += ./src/main.c

#Path for external includes


#Name of final executable
TARGET=Problem1

########## RULES ##########
.PHONY: all

all: 
	$(CC) $(C_SOURCE_FILES) -o $(TARGET)


