CC=g++
CFLAGS=-std=c++11
LDFLAGS=

#Application Source
C++SOURCE_FILES += ./src/main.cpp

#Path for external includes

#Name of final executable
TARGET=Problem10

########## RULES ##########
.PHONY: all

all: 
	$(CC) $(CFLAGS) $(C++SOURCE_FILES) -o $(TARGET)


